/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import java.awt.Color;
import java.awt.Image;

import javax.swing.JPanel;
import javax.swing.JScrollPane;

import com.raven.model.StatusType;
import com.raven.swing.ScrollBar;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import com.toedter.calendar.JDateChooser;
import javax.swing.JComboBox;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author RAVEN
 */
public class Form_3 extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public Form_3() {
        initComponents();
    //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "스탠다드룸", "Single", "$200000", StatusType.예약});
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "스탠다드룸", "Single", "$200000", StatusType.예약마감});
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "스탠다드룸", "Single", "$200000", StatusType.예약});
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "슈페리어룸(시티뷰)", "Double", "$200000", StatusType.예약});
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "슈페리어룸(시티뷰)", "Double", "$350000", StatusType.예약});
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "슈페리어룸(시티뷰)", "Double", "$350000", StatusType.예약});
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "슈페리어룸(시티뷰)", "Twin", "$500000", StatusType.예약마감});
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "슈페리어룸(시티뷰)", "Twin", "$500000", StatusType.예약});
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "디럭스룸(한강뷰", "Triple", "$600000", StatusType.예약});
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "디럭스룸(한강뷰", "Triple", "$600000", StatusType.예약마감});
        table.addRow(new Object[]{"<html><body><img src=\\\"/com/raven/icon/1.png\\\"></body></html>", "스위트룸(한강뷰)", "Suite", "$700000", StatusType.예약});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	panel = new javax.swing.JLayeredPane();
        panelBorder1 = new com.raven.swing.PanelBorder();
        Title = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        table.setRowSelectionAllowed(false);

        setBackground(new java.awt.Color(242, 242, 242));

        panel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        Title.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(127, 127, 127));
        Title.setText("Reservation");

        //필터기능
        JLabel lblNewLabel = new JLabel("체크인 날짜");
        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
        
        JDateChooser dateChooser = new JDateChooser();
        
        lblNewLabel_1 = new JLabel("체크아웃 날짜");
        lblNewLabel_1.setHorizontalAlignment(SwingConstants.CENTER);
        
        JDateChooser dateChooser_1 = new JDateChooser();
        
        JLabel lblNewLabel_2 = new JLabel("인원");
        lblNewLabel_2.setHorizontalAlignment(SwingConstants.CENTER);
        
        String person[] = {"1","2","3","4"};
        JComboBox comboBox = new JComboBox(person);
        
        
        JButton btnNewButton = new JButton("적용");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        
        //룸리스트
        spTable.setBorder(null);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ROOM", "NAME", "BED TYPE", "PRICE", "RESERVATION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);
        
        
        
        

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1Layout.setHorizontalGroup(
        	panelBorder1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelBorder1Layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(panelBorder1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(panelBorder1Layout.createSequentialGroup()
        					.addComponent(spTable)
        					.addContainerGap())
        				.addGroup(panelBorder1Layout.createSequentialGroup()
        					.addGroup(panelBorder1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(panelBorder1Layout.createSequentialGroup()
        							.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(dateChooser, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(dateChooser_1, GroupLayout.PREFERRED_SIZE, 141, GroupLayout.PREFERRED_SIZE)
        							.addGap(47)
        							.addComponent(lblNewLabel_2, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(51)
        							.addComponent(btnNewButton))
        						.addComponent(Title))
        					.addGap(35))))
        );
        panelBorder1Layout.setVerticalGroup(
        	panelBorder1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelBorder1Layout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(Title)
        			.addGap(26)
        			.addGroup(panelBorder1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(panelBorder1Layout.createParallelGroup(Alignment.LEADING, false)
        					.addGroup(panelBorder1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(btnNewButton)
        						.addComponent(lblNewLabel_2, GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        						.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(dateChooser, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(panelBorder1Layout.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(lblNewLabel_1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(dateChooser_1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(spTable, GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        			.addContainerGap())
        );
        panelBorder1.setLayout(panelBorder1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLayeredPane panel;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    private JLabel lblNewLabel_1;
}
