package view.form;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.text.SimpleDateFormat;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JComboBox;
import javax.swing.JCheckBox;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

import view.form.Form_Reservation;
import view.form.Form_RoomReservation;
import modelManager.ReservationManager;
import modelManager.RoomManager;

public class Form_GetReservationInfo extends javax.swing.JPanel {
	
	String checkIn = "";
	
	public Form_GetReservationInfo(String checkin) {
		// TODO Auto-generated constructor stub
		initComponents();
		checkIn = checkin;
	}
	Form_Reservation r = new Form_Reservation();
	
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	panel = new javax.swing.JLayeredPane();
        panelBorder1 = new view.swing.PanelBorder();
        Title = new javax.swing.JLabel();
        
        setBackground(new java.awt.Color(242, 242, 242));

        panel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        
        Title.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(127, 127, 127));
        Title.setText("Reservation");
        
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        
        String person[] = {"1","2","3","4"};
        
        String breakfast[] = {"조식신청 안함","조식신청"};
        
        
        /**************예약 버튼***************/
        JButton RButton = new JButton("예약하기");
        RButton.addMouseListener(new MouseAdapter(){
        	public void mouseClicked(MouseEvent e) {
        		System.out.println("쳌크인: "+checkIn);
        		//d
        	}
        });
        
        

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1Layout.setHorizontalGroup(
        	panelBorder1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelBorder1Layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(panelBorder1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
        					.addComponent(RButton, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
        					.addGap(53))
        				.addGroup(panelBorder1Layout.createSequentialGroup()
        					.addComponent(Title)
        					.addContainerGap(556, Short.MAX_VALUE))))
        );
        panelBorder1Layout.setVerticalGroup(
        	panelBorder1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelBorder1Layout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(Title)
        			.addGap(370)
        			.addComponent(RButton, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder1.setLayout(panelBorder1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JLabel Title;
    private javax.swing.JLayeredPane panel;
    private view.swing.PanelBorder panelBorder1;
}