package view.form;

import java.awt.Color;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import view.model.StatusType;
import view.swing.ScrollBar;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import view.model.StatusType;
import view.swing.ScrollBar;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import com.toedter.calendar.JDateChooser;

import model.Reservation;
import modelManager.ReservationManager;

import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.awt.event.ActionEvent;


public class Form_AdReserv extends javax.swing.JPanel {

	private Reservation[] resList;
	private ReservationManager rM;
	private Reservation res;
    /**
     * Creates new form Form_1
     */
    public Form_AdReserv() {
    	
    	rM = new ReservationManager();
    	initComponents();
    	all();
    }
    	
    	
    	
       
    //  add row table
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JLayeredPane();
        panelBorder1 = new view.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(20, 20, 110, 22);
        spTable = new javax.swing.JScrollPane();
        spTable.setBounds(65, 69, 750, 420);
        table = new view.swing.Table();
        table.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		int row = table.getSelectedRow();
        		
        		
        		
        		String dept = (String) table.getModel().getValueAt(row, 1 );
        		
        		
        		
        	}
        });

        setBackground(new java.awt.Color(242, 242, 242));

        panel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));


        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Reservation");

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "예약번호", "예약자", "방 번호", "체크인 날짜", "체크아웃 날짜","처리현황"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);
        
        lblNewLabel_1_1_1 = new JLabel("처리현황");
        lblNewLabel_1_1_1.setBounds(75, 523, 44, 16);
        
        textField_1 = new JTextField();
        textField_1.setBounds(821, 226, 130, 26);
        textField_1.setColumns(10);
        
        JComboBox ReserveState = new JComboBox();
        ReserveState.setBounds(131, 519, 130, 27);
        
        btnEdit = new JButton("Edit");
        btnEdit.setBounds(301, 518, 75, 29);
        
        btnRefresh = new JButton("Refresh");
        btnRefresh.setBounds(707, 523, 76, 29);
        btnRefresh.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        panelBorder1.setLayout(null);
        panelBorder1.add(jLabel1);
        panelBorder1.add(lblNewLabel_1_1_1);
        panelBorder1.add(textField_1);
        panelBorder1.add(ReserveState);
        panelBorder1.add(spTable);
        panelBorder1.add(btnEdit);
        panelBorder1.add(btnRefresh);
       
    
    }// </editor-fold>//GEN-END:initComponents
    
    private void all() {
    	resList = rM.getAllReservation();
    	for (int i = 0; i < resList.length; ++i) {
        	table.addRow(new Object[] {resList[i].getReservedNo(),resList[i].getMemberID(),resList[i].getRoomNo(),resList[i].getCheckIn(),resList[i].getCheckOut(),resList[i].getReservedStatus()});
        }
    }
    private void set (String name,String loginID, String dept, String phone, Date date) {
    	int i=-1;
    	if(dept.equals("front office"))
    		i=0;
    	else if(dept.equals("housekeeping"))
    		i=1;
    	else if(dept.equals("security"))
    		i=2;
    	else if(dept.equals("hr"))
    		i=3;
    	
    	
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane panel;
    private view.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private view.swing.Table table;
    private JTextField textField_1;
    private JLabel lblNewLabel_1_1_1;
    private JButton btnEdit;
    private JButton btnRefresh;
}
