package view.form;

import java.awt.Color;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import view.swing.ScrollBar;

import javax.swing.ListSelectionModel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;


import model.Employee;
import modelManager.EmployeeManager;

import javax.swing.JButton;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableCellRenderer;


public class Form_AdEmployee extends javax.swing.JPanel {

	private Employee[] emp;
	private EmployeeManager eM;
	
    public Form_AdEmployee() {
    	
        initComponents();
        eM = new EmployeeManager();
        
        //  add row table
        
        all();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JLayeredPane();
        panel.setBounds(20, 20, 907, 0);
        panelBorder1 = new view.swing.PanelBorder();
        panelBorder1.setBounds(20, 40, 907, 557);
        label_title = new javax.swing.JLabel();
        label_title.setBounds(20, 20, 263, 26);
        spTable = new javax.swing.JScrollPane();
        spTable.setBounds(371, 104, 484, 378);
        table = new view.swing.Table();
        table.setFont(new Font("맑은 고딕", Font.PLAIN, 12));
        //테이블 행을 클릭하면 해당 행의 정보가 옆의 박스에 자동 입력되도록 하는 이벤트 리스너
        table.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		int row = table.getSelectedRow();
        		
        		String str = (String) table.getModel().getValueAt(row, 5);
        		SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        		Date strToDate = null;
        		try {
        		    strToDate = formatter.parse(str);
        		} catch (Exception ex) {
        		    throw new RuntimeException(ex);
        		}
        		
        		String dept = (String) table.getModel().getValueAt(row, 1 );
        		String name = (String) table.getModel().getValueAt(row, 2 );
        		String id = (String) table.getModel().getValueAt(row, 3 );
        		String phone = (String) table.getModel().getValueAt(row, 4 );
        		Date date =  strToDate;
        		
        		setInputText(name,id,dept,phone,date);
        		
        	}
        });
        DefaultTableCellRenderer celAlignCenter = new DefaultTableCellRenderer();
		celAlignCenter.setHorizontalAlignment(JLabel.CENTER);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        setBackground(new java.awt.Color(242, 242, 242));

        panel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));


        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        label_title.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        label_title.setForeground(new java.awt.Color(127, 127, 127));
        label_title.setText("Employee Management");

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "고유번호","부서", "이름", "ID", "휴대폰 번호", "생년월일"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);
        table.getColumn("고유번호").setPreferredWidth(70);
        table.getColumn("휴대폰 번호").setPreferredWidth(100);
        
        label_name = new JLabel("이름");
        label_name.setBounds(20, 237, 26, 19);
        label_name.setFont(new Font("맑은 고딕", Font.PLAIN, 13));
        
        label_loginID = new JLabel("아이디");
        label_loginID.setBounds(20, 307, 38, 19);
        label_loginID.setFont(new Font("맑은 고딕", Font.PLAIN, 13));
        
        label_dept = new JLabel("부서");
        label_dept.setBounds(20, 168, 26, 19);
        label_dept.setFont(new Font("맑은 고딕", Font.PLAIN, 13));
        
        label_phone = new JLabel("휴대폰 번호");
        label_phone.setBounds(20, 385, 84, 19);
        label_phone.setFont(new Font("맑은 고딕", Font.PLAIN, 13));
        
        label_birthDate = new JLabel("생년월일");
        label_birthDate.setBounds(20, 458, 84, 19);
        label_birthDate.setFont(new Font("맑은 고딕", Font.PLAIN, 13));
        
        input_name = new JTextField();
        input_name.setBounds(122, 238, 195, 26);
        input_name.setColumns(10);
        
        input_dept = new JComboBox();
        input_dept.setModel(new DefaultComboBoxModel(new String[] {"front office", "housekeeping", "security", "hr"}));
        input_dept.setBounds(122, 168, 195, 26);
        input_dept.setSelectedIndex(-1);
        
        btn_add = new JButton("Add");
        btn_add.setBounds(428, 492, 53, 23);
        
        btn_edit = new JButton("Edit");
        btn_edit.setBounds(537, 492, 51, 23);
        
        btn_del = new JButton("Delete");
        btn_del.setBounds(638, 492, 65, 23);
        
        btn_refresh = new JButton("Refresh");
        btn_refresh.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		refresh();
        	}
        });
        btn_refresh.setBounds(742, 492, 73, 23);
        
        input_loginID = new JTextField();
        input_loginID.setBounds(122, 308, 195, 26);
        input_loginID.setColumns(10);
        
        input_phoneNum = new JTextField();
        input_phoneNum.setBounds(122, 381, 195, 26);
        input_phoneNum.setColumns(10);
        
        input_birthDate = new JDateChooser();
        input_birthDate.setBounds(122, 456, 195, 26);
        
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        setLayout(null);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        add(panelBorder1);
        panelBorder1.setLayout(null);
        panelBorder1.add(label_title);
        panelBorder1.add(label_dept);
        panelBorder1.add(label_phone);
        panelBorder1.add(label_birthDate);
        panelBorder1.add(label_name);
        panelBorder1.add(label_loginID);
        panelBorder1.add(input_loginID);
        panelBorder1.add(input_dept);
        panelBorder1.add(input_name);
        panelBorder1.add(input_phoneNum);
        panelBorder1.add(input_birthDate);
        panelBorder1.add(spTable);
        panelBorder1.add(btn_add);
        panelBorder1.add(btn_edit);
        panelBorder1.add(btn_del);
        panelBorder1.add(btn_refresh);
        add(panel);
        
    }// </editor-fold>//GEN-END:initComponents
   
    private void all() {
    	emp = eM.getAllEmployee();
    	for (int i = 0; i < emp.length; ++i) {
        	table.addRow(new Object[] {emp[i].getEmployeeID(),emp[i].getDepartment(),emp[i].getName(),emp[i].getLoginID(),emp[i].getPhone(),emp[i].getBirthDate()});
        }
    }
    
    //새로고침 버튼
    private void refresh() {
    	DefaultTableModel model = (DefaultTableModel)table.getModel();
    	model.setRowCount(0);
    	all();
    }
    
    private void clear() {
    	input_name.setText("");
    	input_loginID.setText("");
    	input_dept.setSelectedIndex(-1);
    	input_phoneNum.setText("");
    	input_birthDate.setDate(null);
    }
    
    private void setInputText(String name,String id, String dept, String phone, Date date) {
    	int i=-1;
    	if(dept.equals("front office"))
    		i=0;
    	else if(dept.equals("housekeeping"))
    		i=1;
    	else if(dept.equals("security"))
    		i=2;
    	else if(dept.equals("hr"))
    		i=3;
    	
    	input_name.setText(name);
    	input_loginID.setText(id);
    	input_dept.setSelectedIndex(i);
    	input_phoneNum.setText(phone);
    	input_birthDate.setDate(date);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_title;
    private javax.swing.JLayeredPane panel;
    private view.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private view.swing.Table table;
    private JTextField input_name;
    private JTextField input_loginID;
    private JTextField input_phoneNum;
    private JLabel label_dept;
    private JLabel label_phone;
    private JLabel label_birthDate;
    private JLabel label_name;
    private JLabel label_loginID;
    private JComboBox input_dept;
    private JDateChooser input_birthDate;
    private JButton btn_add;
    private JButton btn_edit;
    private JButton btn_del;
    private JButton btn_refresh;
}